name: travel_in_perigord_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  app_links: ^6.4.0
  flutter_dotenv: ^5.1.0
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^3.0.6
  flutter_svg: ^2.0.9
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  latlong2: ^0.9.0
  uuid: ^4.5.1
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  mockito: ^5.0.0
  build_runner: ^2.0.0
  dio: ^5.4.0
  maps_toolkit: ^3.0.0
  freezed_annotation: ^2.4.1
  dart_geohash: ^2.1.0
  provider: ^6.0.0
  polyline_codec: ^0.1.6
  json_annotation: ^4.9.0
  google_fonts: 6.1.0
  glossy: ^0.0.5
  riverpod: ^2.6.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.1
  flutter_custom_tabs: ^2.0.1
  map_launcher: ^3.5.0
  flutter_touch_ripple: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^10.1.0
  async: ^2.11.0
  skeletonizer: ^2.0.0
  riverpod_annotation: ^2.3.5
  infinite_carousel: ^1.1.1
  animations: ^2.0.11
  go_router: ^16.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logos/
